### ISSUE TITLE
pycarl installation failed

### ISSUE THREAD

**Issue by jacktang** [moves-rwth/pycarl#33]
Hello there!

I tried to install stormpy package using `pip` command, it failed and the logs list below:

```
python3 setup.py develop
/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running develop
/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
creating lib/pycarl.egg-info
writing lib/pycarl.egg-info/PKG-INFO
writing dependency_links to lib/pycarl.egg-info/dependency_links.txt
writing requirements to lib/pycarl.egg-info/requires.txt
writing top-level names to lib/pycarl.egg-info/top_level.txt
writing manifest file 'lib/pycarl.egg-info/SOURCES.txt'
reading manifest file 'lib/pycarl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lib/pycarl.egg-info/SOURCES.txt'
running build_ext
Pycarl - Building into build/temp.linux-x86_64-cpython-310
CMake Error at CMakeLists.txt:3 (find_package):
  By not providing "Findcarl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "carl", but
  CMake did not find one.

  Could not find a package configuration file provided by "carl" with any of
  the following names:

    carlConfig.cmake
    carl-config.cmake

  Add the installation prefix of "carl" to CMAKE_PREFIX_PATH or set
  "carl_DIR" to a directory containing one of the above files.  If "carl"
  provides a separate development package or SDK, be sure it has been
  installed.


Traceback (most recent call last):
  File "/srv/Codes/jack/pycarl/setup.py", line 182, in <module>
    setup(
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/srv/Codes/jack/pycarl/setup.py", line 69, in run
    _ = subprocess.check_output(["cmake", os.path.abspath("cmake")] + cmake_args, cwd=build_temp_version)
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/dev/miniconda3/envs/dev/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '/srv/Codes/jack/pycarl/cmake']' returned non-zero exit status 1.
```

How can I fix this? Thanks!

**Comment by volkm** [comment]
Hi,
it seems that the carl installation could not be found. Did you install carl by yourself or automatically via Storm? If you [manually install carl](https://www.stormchecker.org/documentation/obtain-storm/dependencies.html#carl), pycarl should be able to find it.

**Comment by AlanLeAI** [comment]
I have followed all the steps on https://www.stormchecker.org/documentation/obtain-storm/dependencies.html#carl

I still get the error saying that

-- Build files have been written to: /work/cs-grad/tuanle/xSRL/stormpy/pycarl/carl-storm/build/resources/src/Eigen3-EP-build
[ 40%] Performing build step for 'Eigen3-EP'
[ 40%] Performing install step for 'Eigen3-EP'
-- Eigen3-EP install command succeeded.  See also /work/cs-grad/tuanle/xSRL/stormpy/pycarl/carl-storm/build/resources/src/Eigen3-EP-stamp/Eigen3-EP-install-*.log
[ 40%] Completed 'Eigen3-EP'
[ 45%] Built target Eigen3-EP
[ 45%] Built target carl_resources
make[3]: *** No rule to make target 'resources/lib/libginac.so', needed by 'libcarl.so.14.28'.  Stop.
make[2]: *** [CMakeFiles/Makefile2:450: src/carl/CMakeFiles/lib_carl.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:457: src/carl/CMakeFiles/lib_carl.dir/rule] Error 2

**Comment by volkm** [comment]
This issue seems to be related to carl-storm and I moved [the issue](https://github.com/moves-rwth/carl-storm/issues/55).
